compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: "*(pde6dc), which doesn't satisfy what react-scripts*"
  - level: discard
    pattern: "*(p6f2bc), which doesn't satisfy what react-identicons*"
  - level: discard
    pattern: "*(pca8b0), which doesn't satisfy what react-identicons*"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
