# For `forge doc` only which requires running from the top-level folder
[profile.default]
solc = "0.8.30"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 10000

src = 'contracts/src'
out = 'contracts/out'
libs = ['./node_modules', 'contracts/lib']

