version: '3'
services:
  keeper-bot:
    container_name: keeper-bot-${DEPLOYMENT:?error}
    extends:
      file: ../base/bot-pm2.yml
      service: bot-pm2
    volumes:
      - type: bind
        source: ./pm2.config.keeper-bot.${DEPLOYMENT}.js
        target: /usr/src/app/contracts/ecosystem.config.js

  relayer-bot-from-chiado:
    container_name: relayer-bot-from-chiado-${DEPLOYMENT:?error}
    extends:
      file: ../base/bot-pm2.yml
      service: bot-pm2
    volumes:
      - type: bind
        source: ./pm2.config.relayer-bot-from-chiado.${DEPLOYMENT}.js
        target: /usr/src/app/contracts/ecosystem.config.js
    profiles:
      - chiado

  relayer-bot-from-goerli:
    container_name: relayer-bot-from-goerli-${DEPLOYMENT:?error}
    extends:
      file: ../base/bot-pm2.yml
      service: bot-pm2
    volumes:
      - type: bind
        source: ./pm2.config.relayer-bot-from-goerli.${DEPLOYMENT}.js
        target: /usr/src/app/contracts/ecosystem.config.js
    profiles:
      - goerli

  relayer-bot-from-hardhat-host:
    container_name: relayer-bot-from-hardhat-host-${DEPLOYMENT:?error}
    extends:
      file: ../base/bot.yml
      service: bot
    command: bot:relayer-from-hardhat --network dockerhost
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - type: bind
        source: ../../contracts/deployments/localhost
        target: /usr/src/app/contracts/deployments/localhost
    profiles:
      - hardhat
