/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { RNG, RNGInterface } from "../RNG";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_block",
        type: "uint256",
      },
    ],
    name: "contribute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_block",
        type: "uint256",
      },
    ],
    name: "getRN",
    outputs: [
      {
        internalType: "uint256",
        name: "RN",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_block",
        type: "uint256",
      },
    ],
    name: "getUncorrelatedRN",
    outputs: [
      {
        internalType: "uint256",
        name: "RN",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_block",
        type: "uint256",
      },
    ],
    name: "requestRN",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class RNG__factory {
  static readonly abi = _abi;
  static createInterface(): RNGInterface {
    return new utils.Interface(_abi) as RNGInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): RNG {
    return new Contract(address, _abi, signerOrProvider) as RNG;
  }
}
