FROM python:3@sha256:137ae4b9f85671bd912a82a19b6966e2655f73e13579b5d6ad4edbddaaf62a9c

WORKDIR /usr/src/app

COPY requirements.txt src/* ./
RUN pip install --no-cache-dir -r requirements.txt

COPY watchlist/* /var/lib/watchlist/

CMD [ "python", "-u", "./add_hashes.py" ]