FROM python:3@sha256:a8aab6d8cce4d31c10dda046d6d940fc30b64de3438f7969f0db0ab19f3469f9

WORKDIR /usr/src/app

COPY requirements.txt src/* ./
RUN pip install --no-cache-dir -r requirements.txt

COPY watchlist/* /var/lib/watchlist/

CMD [ "python", "-u", "./add_hashes.py" ]