FROM python:3@sha256:02808bfd640d6fd360c30abc4261ad91aacacd9494f9ba4e5dcb0b8650661cf5

WORKDIR /usr/src/app

COPY requirements.txt src/* ./
RUN pip install --no-cache-dir -r requirements.txt

COPY watchlist/* /var/lib/watchlist/

CMD [ "python", "-u", "./add_hashes.py" ]