#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#Abort on first error
set -e

#Get the list of staged files
staged_files=$(git diff --cached --name-only)

#Check if any file is in the kleros-app directory and if so, check types
if echo "$staged_files" | grep -q "^kleros-app/"; then
  yarn workspace @kleros/kleros-app check-types
fi

yarn lint-staged
