#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#Abort on first error
set -e

#Get the list of staged files
staged_files=$(git diff --cached --name-only)

#Check if any file is in the kleros-app directory and if so, check types
if echo "$staged_files" | grep -q "^kleros-app/"; then
  yarn workspace @kleros/kleros-app check-types
fi

#Check if any file is in the kleros-sdk directory and if so, check types
if echo "$staged_files" | grep -q "^kleros-sdk/"; then
  yarn workspace @kleros/kleros-sdk check-types
fi

#Check if any file is in the web-devtools directory and if so, check types
if echo "$staged_files" | grep -q "^web-devtools/"; then
  yarn workspace @kleros/kleros-v2-web-devtools check-types
fi

#Check if any file is in the web directory and if so, check types
if echo "$staged_files" | grep -q "^web/"; then
  yarn workspace @kleros/kleros-v2-web check-types
fi

yarn lint-staged
