name: Contracts Testing

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "kleros-sdk/**"
      - "services/**"
      - "subgraph/**"
      - "web/**"
  pull_request:
    branches:
      - "*"
      
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  contracts-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2.10.2
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          binaries.soliditylang.org:443
          classic.yarnpkg.com:443
          github.com:443
          nightly.yarnpkg.com:443
          nodejs.org:443
          objects.githubusercontent.com:443
          registry.yarnpkg.com:443
          registry.npmjs.org:443
          54.185.253.63:443

    - name: Setup Node.js environment
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 18.x   
        
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive
    
    - name: Cache node modules
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      env:
        cache-name: cache-node-modules
      with:
        path: | 
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-build-${{ secrets.CACHE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ secrets.CACHE_VERSION }}-${{ env.cache-name }}-

    - name: Install contracts dependencies
      run: yarn workspace @kleros/kleros-v2-contracts install

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Run Hardhat and Foundry tests with coverage
      run: yarn coverage
      working-directory: contracts
                   
    - name: Upload a build artifact
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:    
        name: code-coverage-report    
        path: contracts/coverage
