name: Add PR labels

on:
  pull_request:
    types: [opened, edited]
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read
  issues: read
  pull-requests: write

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.5.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            yarnpkg.com:443
            github.com:443
            nightly.yarnpkg.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443
            54.185.253.63:443

      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@f54e957e58fc976eba5ffa36e1a1030572dbb78d # v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        
